export const routes = {
  login: "/login",
  home: "/inicio",
  tenants: "/tenants",
  tenantsNew: "/tenants/new",
  tenantDetail: "/tenants/:tenantId",
  supportUnits: "/catalog/units",
  supportProducts: "/catalog/products",
  reports: "/reports",
  users: "/users",
  farms: "/farms",
  fields: "/fields",
  operations: "/operations",
  metrics: "/metricas",
  fieldReport: "/relatorio-talhao",
  farmPermissions: "/farm-permissions",
  units: "/units",
  products: "/products",
  inventoryLocations: "/inventory/locations",
  inventoryBalance: "/inventory/balance",
  accessDenied: "/access-denied",
} as const;
